[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
   Content-Security-Policy: default-src 'self'; connect-src 'self' https://cryptopulse-backend-ht7y.onrender.com https://api.coingecko.com https://api.alternative.me https://min-api.cryptocompare.com;
  from = "/"
  to = "/index.html"
  status = 200
